CREATE TABLE cdr (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    calldate DATETIME(6) NOT NULL,
    clid VARCHAR(255) NOT NULL DEFAULT '',
    src VARCHAR(80) NOT NULL DEFAULT '',
    dst VARCHAR(80) NOT NULL DEFAULT '',
    dcontext VARCHAR(80) NOT NULL DEFAULT '',
    channel VARCHAR(255) NOT NULL DEFAULT '',
    dstchannel VARCHAR(255) NOT NULL DEFAULT '',
    lastapp VARCHAR(80) NOT NULL DEFAULT '',
    lastdata VARCHAR(255) NOT NULL DEFAULT '',
    duration INT UNSIGNED NOT NULL DEFAULT 0,
    billsec INT UNSIGNED NOT NULL DEFAULT 0,
    disposition VARCHAR(45) NOT NULL DEFAULT '',
    amaflags INT NOT NULL DEFAULT 0,
    accountcode VARCHAR(80) NOT NULL DEFAULT '',
    uniqueid VARCHAR(150) NOT NULL DEFAULT '',
    linkedid VARCHAR(150) NOT NULL DEFAULT '',
    peeraccount VARCHAR(80) NOT NULL DEFAULT '',
    sequence BIGINT UNSIGNED NOT NULL DEFAULT 0,
    userfield VARCHAR(255) NOT NULL DEFAULT '',
    customer_ext VARCHAR(80) NOT NULL DEFAULT '',
    dialed VARCHAR(80) NOT NULL DEFAULT '',
    src_ip VARCHAR(80) NOT NULL DEFAULT '',
    PRIMARY KEY (id),
    KEY cdr_calldate (calldate),
    KEY cdr_customer_date (accountcode, calldate),
    KEY cdr_customer_id (accountcode, id),
    KEY cdr_linkedid (linkedid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
